name: EWTEC_2023
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - appnope=0.1.3
  - asciitree=0.3.3
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrdict=2.0.1
  - attrs=23.1.0
  - autograd=1.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blinker=1.6.2
  - bokeh=3.1.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.05.30
  - cachetools=5.3.0
  - capytaine=1.5
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cloudpickle=2.2.1
  - cmocean=3.0.3
  - colorspacious=1.1.2
  - comm=0.1.3
  - contourpy=1.0.7
  - cryptography=38.0.4
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2022.2.1
  - dask-core=2022.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - distributed=2022.2.1
  - entrypoints=0.4
  - executing=1.2.0
  - fasteners=0.17.3
  - fonttools=4.39.4
  - freetype=2.10.4
  - frozenlist=1.3.3
  - fsspec=2023.5.0
  - future=0.18.3
  - gcsfs=2023.5.0
  - giflib=5.2.1
  - google-api-core=2.11.0
  - google-auth=2.19.1
  - google-auth-oauthlib=1.0.0
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.9.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.5.0
  - googleapis-common-protos=1.57.1
  - grpcio=1.42.0
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - ipykernel=6.23.1
  - ipython=8.14.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - lcms2=2.15
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcxx=16.0.5
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=16.0.5
  - llvmlite=0.40.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numba=0.57.0
  - numcodecs=0.11.0
  - numpy=1.24.3
  - oauthlib=3.2.2
  - openssl=1.1.1t
  - packaging=23.1
  - pandas=2.0.2
  - parso=0.8.3
  - partd=1.4.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=3.5.1
  - pooch=1.7.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=3.20.3
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.7.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=25.1.0
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.10.1
  - setuptools=67.8.0
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tblib=1.7.0
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wavespectra=3.13.0
  - wcwidth=0.2.6
  - wecopttool=2.5.0
  - wheel=0.38.4
  - xarray=2023.5.0
  - xyzservices=2023.5.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.2
  - zarr=2.14.2
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - gmsh==4.11.1
      - markdown-it-py==2.2.0
      - mdurl==0.1.2
      - meshio==5.3.4
      - pygmsh==7.1.17
      - rich==13.4.1
